name       : haskell-microlens-mtl
version    : 0.1.11.1
release    : 3
source     :
    - https://hackage.haskell.org/package/microlens-mtl-0.1.11.1/microlens-mtl-0.1.11.1.tar.gz : d3e74f46a72aad12b71d8549a98fbc023fb364766f17d75742fb32fee70bdf50
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains functions (like view or +=) which work on MonadReader, MonadWriter, and MonadState from the mtl package.
description: |
    This package contains functions (like view or +=) which work on MonadReader, MonadWriter, and MonadState from the mtl package.
builddeps  :
    - haskell-cabal-install
    - haskell-microlens-devel
    - haskell-transformers-compat-devel
rundeps    :
    - devel:
        - haskell-microlens-devel
        - haskell-transformers-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
