name       : haskell-microlens-mtl
version    : 0.1.10.0
release    : 1
source     :
    - https://hackage.haskell.org/package/microlens-mtl-0.1.10.0/microlens-mtl-0.1.10.0.tar.gz : b1dec4f000f324ae3e1915f683577bd53af218a68d07b0acf437def74e14b39d
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains functions (like view or +=) which work on MonadReader, MonadWriter, and MonadState from the mtl package.
description: |
    This package contains functions (like view or +=) which work on MonadReader, MonadWriter, and MonadState from the mtl package.
builddeps  :
    - haskell-cabal-install
    - haskell-microlens
    - haskell-transformers-compat
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
